//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaint
    {
        public int ID { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> SecretaryId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateOfComplaint { get; set; }
        public string Status { get; set; }
    
        public virtual tblMember tblMember { get; set; }
        public virtual tblSecretary tblSecretary { get; set; }
    }
}
