//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblExpens()
        {
            this.tblTransactions = new HashSet<tblTransaction>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AcctId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> GenLedgerId { get; set; }
        public string ModeOfPayment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Narration { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual tblGeneralLedger tblGeneralLedger { get; set; }
        public virtual tblSecretary tblSecretary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
