//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSocietyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSocietyMaster()
        {
            this.tblSecretaries = new HashSet<tblSecretary>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SecretaryId { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> AdminId { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSecretary> tblSecretaries { get; set; }
    }
}
